
name: deploy demo to gh-pages

on:
  push:
    branches: [  ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      
      - name: Build pages
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: dist
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./pages # The folder the action should deploy.
          commit-message: "update: stisla demo"

  
